<?xml version="1.0" encoding="UTF-8"?><testrun name="dict-persistence" project="dict-persistence" tests="40" started="40" failures="1" errors="28" ignored="0">
  <testsuite name="gov.idaho.sboe.services.CatalogFacadeTest" time="0.323">
    <testcase name="testLoadSubtreeXwalk" classname="gov.idaho.sboe.services.CatalogFacadeTest" time="0.285">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.CatalogFacadeTest.setUp(CatalogFacadeTest.java:32)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testFindGlossaryStringString" classname="gov.idaho.sboe.services.CatalogFacadeTest" time="0.01">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.CatalogFacadeTest.setUp(CatalogFacadeTest.java:32)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testFindAllGlossaryTypes" classname="gov.idaho.sboe.services.CatalogFacadeTest" time="0.01">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.CatalogFacadeTest.setUp(CatalogFacadeTest.java:32)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testFindGlossaryChildrenStringString" classname="gov.idaho.sboe.services.CatalogFacadeTest" time="0.009">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.CatalogFacadeTest.setUp(CatalogFacadeTest.java:32)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testFindGlossaryParentsStringString" classname="gov.idaho.sboe.services.CatalogFacadeTest" time="0.008">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.CatalogFacadeTest.setUp(CatalogFacadeTest.java:32)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
  <testsuite name="gov.idaho.sboe.LoadDataTest" time="0.094">
    <testcase name="testDeleteRelationships" classname="gov.idaho.sboe.LoadDataTest" time="0.008">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testExplicitCircularReferenceCheck" classname="gov.idaho.sboe.LoadDataTest" time="0.008">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testFindAllGlossaryTypes" classname="gov.idaho.sboe.LoadDataTest" time="0.007">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testFindGlossaryParents" classname="gov.idaho.sboe.LoadDataTest" time="0.007">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testImplicitCircularReferenceCheck" classname="gov.idaho.sboe.LoadDataTest" time="0.008">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testRolodexSearch" classname="gov.idaho.sboe.LoadDataTest" time="0.008">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testNarrativeUpdate" classname="gov.idaho.sboe.LoadDataTest" time="0.007">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testGlossaryRemove" classname="gov.idaho.sboe.LoadDataTest" time="0.008">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testLoadTheDatabase" classname="gov.idaho.sboe.LoadDataTest" time="0.008">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testDeleteGlossaryCascadeRelationships" classname="gov.idaho.sboe.LoadDataTest" time="0.008">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testNarrativeWildcardSearch" classname="gov.idaho.sboe.LoadDataTest" time="0.008">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testGlossaryCreateTree" classname="gov.idaho.sboe.LoadDataTest" time="0.007">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getEntityManager(JPAResourceBean.java:216)&#13;
	at gov.idaho.sboe.LoadDataTest.setUp(LoadDataTest.java:64)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 19 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 22 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
  <testsuite name="gov.idaho.sboe.AbstractJPA" time="0.001">
    <testcase name="warning" classname="junit.framework.TestSuite.1" time="0.001">
      <failure>junit.framework.AssertionFailedError: No tests found in gov.idaho.sboe.AbstractJPA&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.TestCase.fail(TestCase.java:227)&#13;
	at junit.framework.TestSuite$1.runTest(TestSuite.java:100)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
  <testsuite name="gov.idaho.sboe.utils.DatabaseExport" time="0.444">
    <testcase name="testDumpSomeTables" classname="gov.idaho.sboe.utils.DatabaseExport" time="0.376"/>
    <testcase name="testDumpFullDatabase" classname="gov.idaho.sboe.utils.DatabaseExport" time="0.055"/>
    <testcase name="testDump" classname="gov.idaho.sboe.utils.DatabaseExport" time="0.013">
      <error>java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory&#13;
	at org.dbunit.util.search.AbstractNodesFilterSearchCallback.&lt;init&gt;(AbstractNodesFilterSearchCallback.java:53)&#13;
	at org.dbunit.database.search.AbstractMetaDataBasedSearchCallback.&lt;init&gt;(AbstractMetaDataBasedSearchCallback.java:53)&#13;
	at org.dbunit.database.search.ImportedAndExportedKeysSearchCallback.&lt;init&gt;(ImportedAndExportedKeysSearchCallback.java:42)&#13;
	at org.dbunit.database.search.TablesDependencyHelper.getAllDependentTables(TablesDependencyHelper.java:106)&#13;
	at org.dbunit.database.search.TablesDependencyHelper.getAllDependentTables(TablesDependencyHelper.java:92)&#13;
	at gov.idaho.sboe.utils.DatabaseExport.testDump(DatabaseExport.java:60)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:606)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory&#13;
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)&#13;
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)&#13;
	at java.security.AccessController.doPrivileged(Native Method)&#13;
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)&#13;
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)&#13;
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)&#13;
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)&#13;
	... 25 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
  <testsuite name="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.079">
    <testcase name="testConcatSingleTokenPhrase" classname="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.007">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.NarrativeIndexingFacadeTest.setUp(NarrativeIndexingFacadeTest.java:17)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testBuildWhereAndSelectClause" classname="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.007">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.NarrativeIndexingFacadeTest.setUp(NarrativeIndexingFacadeTest.java:17)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testBuildDoubleWhereOnlyClause" classname="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.007">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.NarrativeIndexingFacadeTest.setUp(NarrativeIndexingFacadeTest.java:17)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testIsOracleStopWordFalse" classname="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.007">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.NarrativeIndexingFacadeTest.setUp(NarrativeIndexingFacadeTest.java:17)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testIsOracleStopWordTrue" classname="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.007">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.NarrativeIndexingFacadeTest.setUp(NarrativeIndexingFacadeTest.java:17)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testBuildWhereOnlyClause" classname="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.009">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.NarrativeIndexingFacadeTest.setUp(NarrativeIndexingFacadeTest.java:17)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testConcatMultipleTokenPhrase" classname="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.008">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.NarrativeIndexingFacadeTest.setUp(NarrativeIndexingFacadeTest.java:17)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testBuildMultiWhereAndSelectClause" classname="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.007">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.NarrativeIndexingFacadeTest.setUp(NarrativeIndexingFacadeTest.java:17)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testTokenizeNarrative" classname="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.009">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.NarrativeIndexingFacadeTest.setUp(NarrativeIndexingFacadeTest.java:17)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testConcatDoubleTokenPhrase" classname="gov.idaho.sboe.services.NarrativeIndexingFacadeTest" time="0.01">
      <error>Local Exception Stack: &#13;
Exception [EclipseLink-30005] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.PersistenceUnitLoadingException&#13;
Exception Description: An exception was thrown while searching for persistence archives with ClassLoader: sun.misc.Launcher$AppClassLoader@1174ec5&#13;
Internal Exception: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionSearchingForPersistenceResources(PersistenceUnitLoadingException.java:127)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:177)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)&#13;
	at gov.idaho.sboe.utils.JPAResourceBean.getFactory(JPAResourceBean.java:181)&#13;
	at gov.idaho.sboe.services.NarrativeIndexingFacadeTest.setUp(NarrativeIndexingFacadeTest.java:17)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:255)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:250)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.RuntimeException: url = [file:/C:/workspaces/IdahoSBOE/dict-persistence/WebContent/WEB-INF/lib/javax.persistence_2.1.0.v201304241213.jar]&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:444)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.buildClassSet(PersistenceUnitProcessor.java:115)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:90)&#13;
	at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:96)&#13;
	... 18 more&#13;
Caused by: java.io.FileNotFoundException: C:\workspaces\IdahoSBOE\dict-persistence\WebContent\WEB-INF\lib\javax.persistence_2.1.0.v201304241213.jar (The system cannot find the path specified)&#13;
	at java.util.zip.ZipFile.open(Native Method)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:215)&#13;
	at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:145)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:153)&#13;
	at java.util.jar.JarFile.&lt;init&gt;(JarFile.java:117)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:93)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.ArchiveFactoryImpl.createArchive(ArchiveFactoryImpl.java:58)&#13;
	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getClassNamesFromURL(PersistenceUnitProcessor.java:431)&#13;
	... 21 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
  <testsuite name="gov.idaho.sboe.EntityBeanTest" time="0.024">
    <testcase name="testUser" classname="gov.idaho.sboe.EntityBeanTest" time="0.001"/>
    <testcase name="testGlossaryXwalkHistory" classname="gov.idaho.sboe.EntityBeanTest" time="0.001"/>
    <testcase name="testGlossaryEquals" classname="gov.idaho.sboe.EntityBeanTest" time="0.001"/>
    <testcase name="testGlossaryType" classname="gov.idaho.sboe.EntityBeanTest" time="0.001"/>
    <testcase name="testGlossaryClone" classname="gov.idaho.sboe.EntityBeanTest" time="0.0"/>
    <testcase name="testGlossaryXwalk" classname="gov.idaho.sboe.EntityBeanTest" time="0.001"/>
    <testcase name="testValidateGlossary" classname="gov.idaho.sboe.EntityBeanTest" time="0.018"/>
    <testcase name="testGlossaryHistory" classname="gov.idaho.sboe.EntityBeanTest" time="0.001"/>
    <testcase name="testGlossaryCompareTo" classname="gov.idaho.sboe.EntityBeanTest" time="0.0"/>
  </testsuite>
</testrun>
